### ISSUE TITLE
Please make consumable as a library

### ISSUE THREAD

**Issue by hoganbc** [asmith26/Vose-Alias-Method#3]
This is precisely the algorithm I'm looking for to use in my production system! But to use it, there's a few things to change to make it useful as a library:

1. Return the sample result in `sample_n()`. It implicitly returns `None` now.
2. Use logging and single line printouts instead of print.
    * With logging, the consuming code turn on or off logging or set the levels to log. With single lines, logs are easily greppable. I think the printout is fine for a script, but it's not neighborly as a library.

If this works for you, I can submit a pull request tomorrow.

**Comment by asmith26** [comment]
Hi @hoganbc,

Thanks for your great suggestions. I particularly think getting `sample_n()` to return something instead of just `None` is a great idea. Pull requests very welcome!

Thanks again

**Comment by hoganbc** [comment]
PR https://github.com/asmith26/Vose-Alias-Method/pull/4

**Comment by asmith26** [comment]
Thanks very much @hoganbc - a great and very clear pull request!

**Comment by hoganbc** [comment]
Thanks!

**Comment by hoganbc** [comment]
Do you mind adding a tag to track the versions? This makes it really nice to know which commits were released with which version.

**Comment by asmith26** [comment]
Happily will - I haven't really used git tags before, what command would you recommend?

**Comment by hoganbc** [comment]
Looks like it's tagged now! The tag subcommand should be pretty straightforward, similar to using the branch subcommand.
